//
// JsonModel.m
//
// Json Mapping Automatically Generated By JsonToolkit Library for Objective C
// Diego Trinciarelli 2011
//

#import "Build.h"
#import "Commit.h"

@implementation Build

@synthesize Status;
@synthesize Created;
@synthesize Deployed;
@synthesize commit;
@synthesize Download_url;
@synthesize Tests_url;
@synthesize Url;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[Build alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    Status = [dictionary objectForKey:@"Status"];
    Created = [dictionary objectForKey:@"Created"];
    Deployed = [dictionary objectForKey:@"Deployed"];
    
    commit = [[Commit alloc] initWithDictionary:[dictionary objectForKey:@"Commit"]];
    Download_url = [dictionary objectForKey:@"Download_url"];
    Tests_url = [dictionary objectForKey:@"Tests_url"];
    Url = [dictionary objectForKey:@"Url"];
  }
  return self;
}


@end